Implement conditional logging
pybee/batavia pull request #514
Opened 2017-05-09 22:05 UTC by whit537

Closes #385 by defining a `debug` helper that logs conditionally based on the presence of 

- [ ] confirm design
- [ ] test it
- [ ] replace commented-out `console.log` calls (also seeing `console.log.info`? is that really a thing?) in other files.

2017-05-09 22:06 UTC, whit537 commented
Ping @glasnt @freakboy3742 for initial review! :-)

2017-05-10 03:09 UTC, freakboy3742 requested changes
Definitely like the idea of abstracting `debug()`. 

Regarding the specific implementation; This is Batavia-specific debug functionality, so I'm wondering if it might be better to put this into the `batavia` namespace (i.e., `batavia.debug()`) to avoid potential collisions. 

There's also the matter of configuration - using process.env is great for deploying inside node, but doesn't help much in the browser. Configuring this as part of [VM initialisation](https://github.com/pybee/batavia/blob/master/batavia/VirtualMachine.js#L15), as something that can be set:

1. by specific argument to the VM instance
2. by inspecting a state variable like `batavia.DEBUG`
3. by inspecting the `process.env` environment

with more specific/local settings taking priority, that would maximise flexibility.

2017-05-10 03:09 UTC, freakboy3742 commented on batavia/batavia.js
> +if (process.env.PYBEE_DEBUG && process.env.PYBEE_DEBUG !== '0') {
BATAVIA_DEBUG would be a better variable name - referring the project, rather than the meta-project.

2017-05-10 03:19 UTC, freakboy3742 commented
Also - the `console.log.info` thing is probably an oversight from some copy-pasta code. I'm a professional. I promise I know what I'm doing. :-)

2017-05-17 09:39 UTC, whit537 commented on batavia/batavia.js
> +if (process.env.PYBEE_DEBUG && process.env.PYBEE_DEBUG !== '0') {
Done in d4d737f60bd16dad4574459cb9f2901cfc5bc762.

2017-05-17 09:45 UTC, whit537 commented
> [I]t might be better to put this into the `batavia` namespace (i.e., `batavia.debug()`) to avoid potential collisions.

Attempted in d4d737f60bd16dad4574459cb9f2901cfc5bc762, but I'm getting the following error from `npm run build`. Looks like `batavia/stdlib` is empty. Is there an additional build step I'm missing?

```
ERROR in ./batavia/batavia.js
Module not found: Error: Can't resolve './stdlib' in '/Users/whit537/personal/pybee/batavia/batavia'
 @ ./batavia/batavia.js 24:20-39

ERROR in ./batavia/builtins/__import__.js
Module not found: Error: Can't resolve '../stdlib' in '/Users/whit537/personal/pybee/batavia/batavia/builtins'
 @ ./batavia/builtins/__import__.js 72:25-45
 @ ./batavia/builtins.js
 @ ./batavia/batavia.js
```

2017-07-05 20:42 UTC, agronauts commented
@whit537 I am currently working on this, would it be possible for you to give me pushing permissions to your branch or should I make a new pull request?

2017-07-05 23:45 UTC, whit537 commented
@agronauts Nice! Invite sent! :-)

2017-07-09 06:28 UTC, agronauts commented
@freakboy3742 Could you have another look please? Debugging flag is set in the settings.py file.

2017-07-23 04:18 UTC, agronauts commented
@freakboy3742 Bump

2020-04-25 02:08 UTC, phildini commented
Hi there! It looks like this PR might be dead, so we're closing it for now. Feel free to re-open it if you'd like to continue, or think about directing your efforts to https://github.com/beeware/briefcase or https://github.com/beeware/toga. Both of these have more active development right now. 😄

2020-04-25 02:08 UTC, closed without merging